### ISSUE TITLE
Infra: Remove _dev:on and _dev:off scripts?

### ISSUE THREAD

**Issue by josoroma-zz** [FormidableLabs/aws-lambda-serverless-reference#23]
Amazing work :)

I was wondering, what is the purpose of:

```
    "_dev:on": "sed -i '' 's/FormidableLabs\\/serverless\\/aws/\\.\\.\\/\\.\\.\\/terraform-aws-serverless/g' terraform/main.tf",

    "_dev:off": "sed -i '' 's/\\.\\.\\/\\.\\.\\/terraform-aws-serverless/FormidableLabs\\/serverless\\/aws/g' terraform/main.tf",
```

and when do we need to run those scripts?

**Comment by ryan-roemer** [comment]
Hi @josoroma and thanks for the kind comments!

You can safely ignore / remove the `_dev*` commands if copying this project. They just enable us to easily and temporarily develop both https://github.com/FormidableLabs/terraform-aws-serverless and this project at the same time. 😄

**Comment by ryan-roemer** [comment]
@tptee -- Do you think we should remove the `package.json:scripts._dev*` commands to avoid confusion?

**Comment by josoroma-zz** [comment]
Hi @tptee 

That would perhaps be very good to avoid confusion.

Thanks a bunch Ryan.

**Comment by ryan-roemer** [comment]
Closing, as I'm actively using these for development alongside `terraform-aws-serverless`, so we'll have some artifacts not related to the project itself...
