### ISSUE TITLE
yarn tf:service:init is hitting this error: Terraform initialized in an empty directory!

### ISSUE THREAD

**Issue by josoroma-zz** [FormidableLabs/aws-lambda-serverless-reference#24]
![image](https://user-images.githubusercontent.com/69951/60686216-b1e4f080-9e64-11e9-92ce-eaf60486d9d1.png)

**Comment by josoroma-zz** [comment]
Under Mac:

I am also hitting this one:

![image](https://user-images.githubusercontent.com/69951/60686658-62ec8a80-9e67-11e9-8270-207d7632c44f.png)

**Comment by ryan-roemer** [comment]
What's the full output of your `package.json:scripts` field? You've got some custom commands in there that aren't part of this project.

For example, this project has `yarn tf:terraform ARGS` as the enhanced base for `terraform ARGS` which translates to:

```sh
$ eval $(yarn -s env) && cd terraform && terraform ARGS
```

but you have instead:

```sh
$ eval $(yarn -s env) && cd vpc && terraform ARGS
```

My hunch is that your changes now _don't_ `cd` to a `terraform/**.tf` directory containing terraform files that do stuff...

Maybe backtrack and see if you can get this reference project deployed in your AWS environment without any changes, just setting service name, stage, etc. And _then_ start making changes. If you've got an issue with this project unchanged, we can definitely dig in and diagnose faster!

**Comment by ryan-roemer** [comment]
Does this issue reproduce against this project or one that you've customized?

**Comment by stevenmusumeche** [comment]
Closing due to no response. @josoroma please re-open if the issue re-occurs.
